<a href="https://colab.research.google.com/github/hhaider15/SSI-stacked-ensemble-predictive-algorithmic-model/blob/main/Code%20Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

The code delineates the development of stacked ensemble algorithmic model that predicts SSI after posterior lumbar surgery (laminectomy and/or discectomy) without fusion for spinal degenertive diseases.

We welcome the model to be explored by the scientific community via its implementation on diverse patient populations and spine pathologies.





Developed by:
Ali Haider Bangash MBBS1, Rafael De la Garza Ramos MD1,2

1 Spine Research Group, Montefiore Medical Center, Albert Einstein College of Medicine, Bronx, NY, USA
2 Department of Neurosurgery, Montefiore Medical Center, Albert Einstein College of Medicine, Bronx, NY, USA

In [ ]:
pip install mljar-supervised

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from supervised.automl import AutoML

df = pd.read_csv(
    "Data.csv")
df

,Age,"Male 1, Female 0",Body height (cm),Body weight (kg),BMI,ASA score,Diabetes,Hemodialysis,Smoking,Steroid,...,Revision surgery,Dural tear,Endoscopic tubular surgery,Use of a microscope,Bio-clean room,Emergency surgery,Operative time,Intraoperative bleeding,Administration of CEZ,SSI
0,18,1,178.0,57.0,17.990153,1,0,0,0,0,...,0,0,1,0,0,0,100,20,1,0
1,18,0,154.0,83.0,34.997470,1,0,0,0,0,...,0,0,0,1,1,0,94,150,1,0
2,18,1,177.3,61.8,19.659434,1,0,0,0,0,...,0,0,1,0,0,0,58,1,1,0
3,18,1,170.4,66.9,23.040237,1,0,0,0,0,...,0,0,1,0,0,0,67,1,1,0
4,18,1,176.2,56.6,18.230754,1,0,0,0,0,...,0,0,1,0,0,0,58,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4022,91,0,151.0,44.0,19.297399,2,0,0,0,0,...,0,0,0,0,0,0,120,150,1,0
4023,92,1,165.0,62.6,22.993572,2,0,0,0,0,...,0,0,0,0,0,0,164,160,1,0
4024,92,1,152.0,52.0,22.506925,2,0,0,0,0,...,0,0,0,0,1,0,87,550,1,0
4025,92,1,163.0,54.0,20.324438,2,0,0,0,0,...,0,0,0,0,1,0,76,190,1,0
4026,94,1,158.0,64.0,25.636917,2,0,0,0,0,...,0,1,0,0,1,0,96,150,1,0

In [ ]:
x=df.drop('SSI', axis=1)
y=df.SSI

X_train, X_test, y_train, y_test = train_test_split(
    x, y, test_size=0.01
)

automl = AutoML(mode='Compete', explain_level = 2, eval_metric = 'average_precision')
automl.fit(X_train, y_train)

predictions = automl.predict(X_test)

In [ ]:
import pandas as pd
# scikit learn utilites
from sklearn.datasets import load_digits
from sklearn.metrics import roc_auc_score
from sklearn.metrics import log_loss
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import matthews_corrcoef
from sklearn.model_selection import train_test_split

In [ ]:
# prompt: Predict AUC of y test

auc = roc_auc_score(y_test, predictions)
print("AUC:", auc)

In [ ]:
# prompt: Predict logloss of y test

log_loss = log_loss(y_test, predictions)
print("Log Loss:", log_loss)

In [ ]:
# prompt: Predict F1 of y test

f1 = f1_score(y_test, predictions)
print("F1:", f1)

In [ ]:
# prompt: Predict accuracy of y test

accuracy = accuracy_score(y_test, predictions)
print("Accuracy:", accuracy)

In [ ]:
# prompt: Predict precision of y test

precision = precision_score(y_test, predictions)
print("Precision:", precision)

In [ ]:
# prompt: Predict recall of y test

recall = recall_score(y_test, predictions)
print("Recall:", recall)

In [ ]:
# prompt: Predict mcc of y test

mcc = matthews_corrcoef(y_test, predictions)
print("MCC:", mcc)

In [ ]:
# prompt: load test dataset that does not have outcome variable and predict the outcome

import pandas as pd
test_data = pd.read_csv("test_data.csv")
predictions = automl.predict(test_data)

In [ ]:
# prompt: Save the developed enemble stacked model.

import pickle

# Save the model to a file
with open('model.pkl', 'wb') as file:
    pickle.dump(automl, file)

# Load the model from the file
with open('model.pkl', 'rb') as file:
    loaded_model = pickle.load(file)

In [ ]:
# prompt: load test dataset that does not have outcome variable and predict the outcome

import pandas as pd
test_data = pd.read_csv("test_data.csv")
predictions = loaded_model.predict(test_data)